site_name: Kiuâ€™s Blog
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.top
    - toc.integrate

plugins:
  - search
  - blogging:
      blog_dir: blog
      post_template: templates/post.html
      categories_allowed:
        - tech
        - diary
        - travel
        - notes
        - life
      use_git_date: true
      ignore_errors: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Blog:
      - All Posts: blog/index.md
  - Categories:
      - Tech: blog/categories/tech.md
      - Diary: blog/categories/diary.md
      - Travel: blog/categories/travel.md
      - Notes: blog/categories/notes.md
      - Life: blog/categories/life.md
