site_name: Kiu’s Blog
site_url: https://kiu795.github.io/mysite/

theme:
  name: material
  language: en
  custom_dir: overrides

plugins:
  - search
  - blogging    # 使用最基本形式，不带额外不支持字段

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

extra_css:
  - stylesheets/cards.css

nav:
  - Home: index.md
  - Blog:
      - All Posts: blog/index.md
