site_name: Kiu's Site
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.sections
    # ❗ instant navigation 会和 blog 分页冲突，所以必须关掉
    # - navigation.instant

plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      categories: true
      authors: false

nav:
  - Home: index.md
  - Blog:
      - All Posts: blog/index.md
      - Categories:
          - Diary: blog/categories/diary.md
          - Life: blog/categories/life.md
          - Tech: blog/categories/tech.md
          - Travel: blog/categories/travel.md
          - Notes: blog/categories/notes.md
